--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/4/2022 7:56:44 AM
-- Server version: 5.7.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO quickbilling.account_mappings(id, name, type, label, account_id, created_at, updated_at) VALUES
(1, 'sales_revenue', 'Sales', 'Sales Revenue', 59, NULL, '2022-04-22 07:38:50'),
(3, 'sales_disccount', 'Sales', 'Sales Discount', 60, NULL, '2022-04-22 07:38:50'),
(4, 'sales_return', 'Sales', 'Sales Return', 61, NULL, '2022-04-22 07:38:50'),
(5, 'sales_shipping', 'Sales', 'Sales Shipping', 75, NULL, '2022-04-22 07:38:50'),
(6, 'unearned_revenue', 'Sales', 'Unearned Revenue', 39, NULL, '2022-04-22 07:38:50'),
(7, 'unbilled_sales', 'Sales', 'Unbilled Sales', 62, NULL, '2022-04-22 07:38:50'),
(8, 'unbilled_receiveable', 'Sales', 'Unbilled Receivable', 5, NULL, '2022-04-22 07:38:50'),
(9, 'sales_tax_payable', 'Sales', 'Sales Tax Payable', 44, NULL, '2022-04-22 07:38:50'),
(10, 'purchase_cogs', 'Purchase', 'Purchase (COGS)', 63, NULL, '2022-04-22 07:38:50'),
(11, 'purchase_shipping', 'Purchase', 'Purchase Shipping', 66, NULL, '2022-04-22 07:38:50'),
(12, 'prepayment', 'Purchase', 'Prepayment', 12, NULL, '2022-04-22 07:38:50'),
(13, 'purchase_payable', 'Purchase', 'Unbilled Payable', 35, NULL, '2022-04-22 07:38:50'),
(14, 'unbilled_payable', 'Purchase', 'Purchase Tax Receivable', 14, NULL, '2022-04-22 07:38:50'),
(15, 'account_receiveable', 'AR/AP', 'Account Receivable', 4, NULL, '2022-04-22 07:38:50'),
(16, 'account_payable', 'AR/AP', 'Account Payable', 34, NULL, '2022-04-22 07:38:50'),
(17, 'inventory', 'Inventory', 'Inventory', 7, NULL, '2022-04-22 07:38:50'),
(18, 'inventory_general', 'Inventory', 'Inventory General', 79, NULL, '2022-04-22 07:38:50'),
(19, 'inventory_waste', 'Inventory', 'Inventory Waste', 71, NULL, '2022-04-22 07:38:50'),
(20, 'inventory_production', 'Inventory', 'Inventory Production', 68, NULL, '2022-04-22 07:38:50'),
(21, 'opening_balance_equity', 'Others', 'Opening Balance Equity', 58, NULL, '2022-04-22 07:38:50'),
(22, 'fixed_asset', 'Others', 'Fixed Asset', 23, NULL, '2022-04-22 07:38:50'),
(23, 'bank_revalutation', 'Multi-Currency', 'Bank Revaluation', 83, NULL, '2022-04-22 07:38:50'),
(24, 'realised_gain_loss', 'Multi-Currency', 'Realised Gain/Loss', 85, NULL, '2022-04-22 07:38:50'),
(25, 'unrealised_gain_loss', 'Multi-Currency', 'Unrealised Gain/Loss', 84, NULL, '2022-04-22 07:38:50');