--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/4/2022 7:56:56 AM
-- Server version: 5.7.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO quickbilling.categories(id, entity_id, name, code, type, color, enabled, created_by, created_at, updated_at, deleted_at) VALUES
(1, 1, 'Design', '', 'Item Category', '', 1, 1, '2022-03-10 12:21:15', '2022-03-11 02:54:37', NULL),
(3, 1, 'Food', 'SERVICE', 'Item Category', '', 1, 1, '2022-03-10 12:22:00', '2022-03-11 02:54:37', NULL),
(20, 1, 'Account Receivable (A/R)', 'ACCOUNT RECEIVA...', 'Account Category', '', 1, 1, '2022-03-11 06:12:19', '2022-03-12 03:34:20', NULL),
(21, 1, 'Other Current Assets', 'OTHER CURRENT A...', 'Account Category', '', 1, 1, '2022-03-11 06:12:19', '2022-03-12 03:34:20', NULL),
(22, 1, 'Cash & Bank', 'CASH & BANK', 'Account Category', '', 1, 1, '2022-03-11 06:12:19', '2022-03-12 03:34:20', NULL),
(23, 1, 'Inventory', 'INVENTORY', 'Account Category', '', 1, 1, '2022-03-11 06:12:19', '2022-03-12 03:34:20', NULL),
(24, 1, 'Fixed Assets', 'FIXED ASSETS', 'Account Category', '', 1, 1, '2022-03-11 06:12:19', '2022-03-12 03:34:20', NULL),
(25, 1, 'Other Assets', 'OTHER ASSETS', 'Account Category', '', 1, 1, '2022-03-11 06:12:19', '2022-03-12 03:34:20', NULL),
(26, 1, 'Depreciation & Amortization', 'DEPRECIATION &...', 'Account Category', '', 1, 1, '2022-03-11 06:12:19', '2022-03-12 03:34:20', NULL),
(27, 1, 'Account Payable (A/P)', 'ACCOUNT PAYABLE...', 'Account Category', '', 1, 1, '2022-03-11 06:12:19', '2022-03-12 03:34:20', NULL),
(28, 1, 'Credit Card', 'CREDIT CARD', 'Account Category', '', 1, 1, '2022-03-11 06:12:19', '2022-03-12 03:34:20', NULL),
(29, 1, 'Other Current Liabilities', 'OTHER CURRENT L...', 'Account Category', '', 1, 1, '2022-03-11 06:12:19', '2022-03-12 03:34:20', NULL),
(30, 1, 'Equity', 'EQUITY', 'Account Category', '', 1, 1, '2022-03-11 06:12:19', '2022-03-12 03:34:20', NULL),
(31, 1, 'Income', 'INCOME', 'Account Category', '', 1, 1, '2022-03-11 06:12:19', '2022-03-12 03:34:20', NULL),
(32, 1, 'Other Income', 'OTHER INCOME', 'Account Category', '', 1, 1, '2022-03-11 06:12:19', '2022-03-12 03:34:20', NULL),
(33, 1, 'Cost Of Sales', 'COST OF SALES', 'Account Category', '', 1, 1, '2022-03-11 06:12:19', '2022-03-12 03:34:20', NULL),
(34, 1, 'Expenses', 'EXPENSES', 'Account Category', '', 1, 1, '2022-03-11 06:12:19', '2022-03-12 03:34:20', NULL),
(35, 1, 'Other Expense', 'OTHER EXPENSE', 'Account Category', '', 1, 1, '2022-03-11 06:12:19', '2022-03-12 03:34:20', NULL),
(36, 1, 'Long Term Liabilities', 'LONG TERM LIABI...', 'Account Category', '', 1, 1, '2022-03-12 03:34:20', '2022-03-12 03:34:20', NULL);