--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/4/2022 7:57:00 AM
-- Server version: 5.7.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO quickbilling.contact_banks(id, contact_id, bank_id, contact_account_name, contact_account_number, branch, created_at, updated_at) VALUES
(5, 5, 4, '33333', '33dfsdf', NULL, '2022-03-13 13:32:17', '2022-03-13 13:32:17'),
(7, 7, 7, '232323', 'eqqq', 'test', '2022-03-13 14:39:25', '2022-03-28 14:52:55'),
(9, 7, 1, 'jdjdjjsj', 'eerre', 'morowali', '2022-03-28 15:05:42', '2022-03-28 15:05:42');