--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/4/2022 7:56:59 AM
-- Server version: 5.7.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO quickbilling.contacts(id, entity_id, type, name, email, user_id, company_name, tax_number, phone, fax, identify_by, identify, first_name, middle_name, last_name, identify_number, address, shipping_address, country, state, zip_code, city, website, currency_code, enabled, reference, receivable_account_id, payable_account_id, payment_term_id, max_payable, active_max_payable, can_login, created_at, updated_at, deleted_at) VALUES
(5, 1, 'Customer', 'PT JAYA KUSUMA', NULL, NULL, 'Codingofcents', '34326345', '0812424333', 'weqew', 'National ID', 'Mr.', 'Wayan', 'qqwewq', 'Tisna', '34234324', 'Jl Hayam Wuruk 126 Hotel Jayakarta Tower Lt 21,Mangga Besar, No Jl Hayam Wuruk 126 Hotel Jayakarta Tower Lt 21,Mangga Besar', 'Kamiwangi', NULL, NULL, NULL, NULL, NULL, 'IDR', 1, NULL, 4, 34, 1, 34.3400, 1, 0, '2022-03-13 13:32:17', '2022-03-28 15:24:36', NULL),
(7, 1, 'Customer', 'PT JAYA INVESTAMA', 'jaya1@gmail.com', NULL, 'Codingofcents', '23344', '0812424333', 'qwewqe', 'National ID', 'Ms.', 'Wayan', NULL, 'Tisna', '3213123', 'JL Patra Raya No. 26, West Jakarta, No JL Patra Raya No. 26, West Jakarta', 'Kamiwangi', NULL, NULL, NULL, NULL, NULL, 'IDR', 1, NULL, 4, 34, 3, 2132.2200, 1, 1, '2022-03-13 14:39:25', '2022-04-22 07:51:39', NULL),
(12, 1, 'Vendor', 'PT TEST VENDOR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'JL Patra Raya No. 26, West Jakarta, No JL Patra Raya No. 26, West Jakarta', 'JL Patra Raya No. 26, West Jakarta, No JL Patra Raya No. 26, West Jakarta', NULL, NULL, NULL, NULL, NULL, 'IDR', 1, NULL, NULL, NULL, NULL, 0.0000, 0, 0, '2022-03-15 08:14:15', '2022-03-28 15:24:55', NULL);