--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/4/2022 7:57:01 AM
-- Server version: 5.7.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO quickbilling.contact_emails(id, contact_id, email, created_at, updated_at) VALUES
(1, 5, 'emaiald@ramil.com', '2022-03-13 13:32:17', '2022-03-13 13:32:17'),
(2, 5, 'erere@sdfd.com', '2022-03-13 13:32:17', '2022-03-13 13:32:17'),
(5, 7, 'katahati.work@gmail.com', '2022-03-13 14:39:25', '2022-03-13 14:39:25');