--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/4/2022 7:57:08 AM
-- Server version: 5.7.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO quickbilling.document_item_taxes(id, entity_id, type, document_id, document_item_id, tax_id, name, amount, created_by, created_at, updated_at, deleted_at) VALUES
(1, 1, 'SQ', 3, 2, 1, 'PPN', 950400.0000, NULL, '2022-04-11 12:28:55', '2022-04-22 08:12:18', NULL),
(4, 1, 'SQ', 5, 4, 1, 'PPN', 1650000.0000, NULL, '2022-04-15 01:02:46', '2022-04-22 08:11:47', NULL),
(5, 1, 'SQ', 6, 3, 1, 'PPN', 313500.0000, NULL, '2022-04-15 01:04:56', '2022-04-15 01:04:56', NULL),
(6, 1, 'SQ', 4, 5, 1, 'PPN', 1254000.0000, NULL, '2022-04-15 01:07:15', '2022-04-22 08:11:15', NULL),
(7, 1, 'SQ', 9, 6, 1, 'PPN', 418000.0000, NULL, '2022-04-15 01:32:47', '2022-04-15 01:32:47', NULL),
(8, 1, 'SO', 10, 7, 1, 'PPN', 418000.0000, NULL, '2022-04-15 01:41:37', '2022-04-15 12:25:11', '2022-04-15 12:25:11'),
(9, 1, 'SO', 11, 8, 1, 'PPN', 418000.0000, NULL, '2022-04-15 14:00:11', '2022-04-15 14:01:25', '2022-04-15 14:01:25'),
(10, 1, 'SO', 12, 9, 1, 'PPN', 313500.0000, NULL, '2022-04-15 14:58:15', '2022-04-15 14:58:15', NULL);