--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/4/2022 7:57:07 AM
-- Server version: 5.7.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO quickbilling.document_items(id, entity_id, type, document_id, item_id, name, description, sku, quantity, unit, price, tax, tax_name, tax_rate, discount_type, discount_rate, total, created_by, created_at, updated_at, deleted_at) VALUES
(2, 1, 'SQ', 3, 4, 'Test Item 1', 'test desc', 'ITM-00003', 3.000, 'Project', 3000000.0000, 1, 'PPN', NULL, 'normal', 0.0000, 9000000.0000, 1, '2022-04-11 12:28:55', '2022-04-22 08:12:18', NULL),
(3, 1, 'SQ', 6, 4, 'Test Item 1', 'test desc', 'ITM-00003', 1.000, 'Project', 3000000.0000, 1, 'PPN', NULL, 'normal', 0.0000, 3000000.0000, 1, '2022-04-12 05:53:38', '2022-04-15 01:04:56', NULL),
(4, 1, 'SQ', 5, 2, 'Jasa Website', 'Lorem ipsum dolor sit amet,', 'ITM-00001', 5.000, 'Project', 3000000.0000, 1, 'PPN', NULL, 'normal', 0.0000, 15000000.0000, 1, '2022-04-15 01:02:46', '2022-04-22 08:11:47', NULL),
(5, 1, 'SQ', 4, 5, 'test item 2', 'Lorem ipsum dolor sit amet,', 'ITM-00004', 3.000, 'Project', 4000000.0000, 1, 'PPN', NULL, 'normal', 0.0000, 12000000.0000, 1, '2022-04-15 01:07:15', '2022-04-22 08:11:15', NULL),
(6, 1, 'SQ', 9, 5, 'test item 2', 'Lorem ipsum dolor sit amet,', 'ITM-00004', 1.000, 'Project', 4000000.0000, 1, 'PPN', NULL, 'normal', 0.0000, 4000000.0000, 1, '2022-04-15 01:32:47', '2022-04-15 01:32:47', NULL),
(7, 1, 'SO', 10, 5, 'test item 2', 'Lorem ipsum dolor sit amet,', 'ITM-00004', 1.000, 'Project', 4000000.0000, 1, 'PPN', NULL, 'normal', 0.0000, 4000000.0000, 1, '2022-04-15 01:41:37', '2022-04-15 12:25:11', '2022-04-15 12:25:11'),
(8, 1, 'SO', 11, 5, 'test item 2', 'Lorem ipsum dolor sit amet,', 'ITM-00004', 1.000, 'Project', 4000000.0000, 1, 'PPN', NULL, 'normal', 0.0000, 4000000.0000, 1, '2022-04-15 14:00:11', '2022-04-15 14:01:25', '2022-04-15 14:01:25'),
(9, 1, 'SO', 12, 4, 'Test Item 1', 'test desc', 'ITM-00003', 1.000, 'Project', 3000000.0000, 1, 'PPN', NULL, 'normal', 0.0000, 3000000.0000, 1, '2022-04-15 14:58:15', '2022-04-15 14:58:15', NULL);