--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/4/2022 7:57:12 AM
-- Server version: 5.7.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO quickbilling.files(id, company_id, filename, extension, directory, fileable_type, fileable_id, created_at, updated_at) VALUES
(1, 1, '11653707766.jpg', 'jpg', 'http://localhost:3001/files/files/11653707766.jpg', 'document', 0, '2022-05-28 03:16:06', '2022-05-28 03:16:06');