--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/4/2022 7:57:31 AM
-- Server version: 5.7.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO quickbilling.ifrs_vats(id, entity_id, account_id, code, name, rate, destroyed_at, deleted_at, created_at, updated_at) VALUES
(1, 1, 73, 'P', 'PPN', 11.0000, NULL, NULL, '2022-04-11 05:46:37', '2022-04-22 07:37:39');