--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/4/2022 7:57:29 AM
-- Server version: 5.7.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO quickbilling.reporting_periods(id, entity_id, period_count, status, calendar_year, destroyed_at, deleted_at, created_at, updated_at, closing_date) VALUES
(1, 1, 8, 'OPEN', 2021, NULL, NULL, '2022-04-11 00:34:54', '2022-04-11 00:41:11', '2021-12-31 00:00:00'),
(2, 1, 12, 'OPEN', 2022, NULL, NULL, '2022-04-11 00:47:13', '2022-04-11 00:47:24', '2022-12-31 00:00:00');
