--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/4/2022 7:57:26 AM
-- Server version: 5.7.24
-- Client version: 4.1
--


SET NAMES 'utf8';