--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/4/2022 7:57:28 AM
-- Server version: 5.7.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO quickbilling.ifrs_recycled_objects(id, entity_id, user_id, recyclable_id, recyclable_type, destroyed_at, deleted_at, created_at, updated_at) VALUES
(1, 1, 1, 71, 'IFRS\\Models\\Account', NULL, NULL, '2022-04-11 03:42:28', '2022-04-11 03:42:28');