--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/4/2022 7:57:24 AM
-- Server version: 5.7.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO quickbilling.entities(id, currency_id, parent_id, name, multi_currency, mid_year_balances, year_start, destroyed_at, deleted_at, created_at, updated_at, locale) VALUES
(1, 3, NULL, 'PT Coding Of cents', 0, 0, 2, NULL, NULL, '2022-04-07 01:29:20', '2022-05-07 17:24:34', 'en_GB');
