--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/4/2022 7:57:40 AM
-- Server version: 5.7.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO quickbilling.item_categories(id, category_id, item_id, created_at, updated_at) VALUES
(1, 0, 4, '2022-03-15 15:04:16', '2022-03-15 15:04:16'),
(2, 3, 5, '2022-03-15 15:10:29', '2022-03-15 15:10:29'),
(3, 1, 5, '2022-03-15 15:10:29', '2022-03-15 15:10:29'),
(4, 3, 4, '2022-03-16 06:04:02', '2022-03-16 06:04:02'),
(5, 1, 4, '2022-03-16 06:04:02', '2022-03-16 06:04:02'),
(6, 3, 6, '2022-03-16 06:27:53', '2022-03-16 06:27:53'),
(7, 1, 3, '2022-03-16 06:36:21', '2022-03-16 06:36:21'),
(8, 1, 2, '2022-03-16 06:36:35', '2022-03-16 06:36:35'),
(9, 3, 2, '2022-03-16 06:36:35', '2022-03-16 06:36:35');