--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/4/2022 7:57:39 AM
-- Server version: 5.7.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO quickbilling.items(id, entity_id, item_group_id, code, name, unit, image, description, sale_price, purchase_price, quantity, minimum_stock, category_id, buy_tax_id, sell_tax_id, buy_account_id, sell_account_id, tract_stock, inventory_account, enabled, created_by, temp_id, created_at, updated_at, deleted_at) VALUES
(1, 1, 0, '-', 'Bandwidth Internet', 'Project', '', 'test', 2000000.0000, 324444.4400, 0, 0.0000, NULL, 0, 0, NULL, NULL, 0, NULL, 1, 1, NULL, '2022-04-22 07:39:47', '2022-04-22 07:39:47', NULL),
(2, 1, 0, 'ITM-00001', 'Jasa Website', 'Project', '', 'Lorem ipsum dolor sit amet,', 0.0000, 0.0000, 0, 0.0000, NULL, 1, 1, NULL, NULL, 0, NULL, 1, 1, NULL, '2022-03-17 03:34:44', '2022-03-17 03:34:44', NULL),
(3, 1, 0, 'ITM-00002', 'Tarik Kabel', 'Project', '', 'Lorem ipsum dolor sit amet,', 0.0000, 0.0000, 0, 0.0000, NULL, 1, 1, NULL, NULL, 0, NULL, 1, 1, NULL, '2022-03-17 03:34:39', '2022-03-17 03:34:39', NULL),
(4, 1, 0, 'ITM-00003', 'Test Item 1', 'Project', '', 'test desc', 3000000.0000, 10000.0000, 0, 3.3300, NULL, 1, 1, 7, 7, 0, 8, 1, 1, NULL, '2022-03-19 07:39:55', '2022-03-19 07:39:55', NULL),
(5, 1, 0, 'ITM-00004', 'test item 2', 'Project', '', 'Lorem ipsum dolor sit amet,', 4000000.0000, 2323222.2200, 0, 3.3300, NULL, 1, 2, 34, 59, 0, 7, 1, 1, NULL, '2022-03-19 07:40:27', '2022-03-19 07:40:27', NULL),
(6, 1, 0, 'ITM-00005', 'item kedua', 'Project', '', 'Lorem ipsum dolor sit amet,', NULL, NULL, 0, 0.0000, NULL, 1, 1, NULL, 45, 0, NULL, 1, 1, 262724503967, '2022-04-14 12:45:25', '2022-04-14 12:45:25', NULL);