--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/4/2022 7:57:44 AM
-- Server version: 5.7.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO quickbilling.migrations(id, migration, batch) VALUES
(1, '2014_10_12_000000_create_users_table', 1),
(2, '2014_10_12_000000_ifrs_create_or_update_users_table', 1),
(3, '2014_10_12_100000_create_password_resets_table', 1),
(4, '2014_10_12_200000_add_two_factor_columns_to_users_table', 1),
(5, '2019_08_19_000000_create_failed_jobs_table', 1),
(6, '2019_12_14_000001_create_personal_access_tokens_table', 1),
(7, '2020_01_09_200440_create_ifrs_entities_table', 1),
(8, '2020_01_09_212616_create_ifrs_currencies_table', 1),
(9, '2020_01_10_182721_create_ifrs_exchange_rates_table', 1),
(10, '2020_01_10_204541_create_ifrs_reporting_periods_table', 1),
(11, '2020_01_10_213405_create_ifrs_recycled_objects_table', 1),
(12, '2020_01_16_152746_create_ifrs_categories_table', 1),
(13, '2020_01_16_215416_create_ifrs_accounts_table', 1),
(14, '2020_01_17_113024_create_ifrs_vats_table', 1),
(15, '2020_01_21_202744_create_ifrs_balances_table', 1),
(16, '2020_01_22_115407_create_ifrs_transactions_table', 1),
(17, '2020_01_22_201904_create_ifrs_assignments_table', 1),
(18, '2020_02_09_131007_create_ifrs_line_items_table', 1),
(19, '2020_02_09_131135_create_ifrs_ledgers_table', 1),
(20, '2021_03_04_194118_add_entity_locale', 1),
(21, '2021_04_30_183324_rename_amount_column', 1),
(22, '2021_04_30_200319_add_rate_column', 1),
(23, '2021_06_04_155845_create_closing_rates_table', 1),
(24, '2021_06_11_202626_add_closing_rate_column', 1),
(25, '2021_06_12_211003_create_closing_transactions_table', 1),
(26, '2021_08_25_191550_add_compound_transaction_columns', 1),
(27, '2021_08_25_192141_add_line_item_entry_column', 1),
(28, '2021_12_28_115835_create_sessions_table', 1),
(29, '2021_12_29_104510_create_permission_tables', 1),
(30, '2022_01_26_021932_create_attachments_table', 1),
(31, '2022_02_11_082019_create_audits_table', 1),
(32, '2022_02_26_084303_add_company_to_business_partners_table', 1),
(33, '2022_02_28_102500_create_billing_table', 1),
(34, '2022_03_01_014401_create_documents_table', 1),
(35, '2022_03_11_161945_create_banks_table', 1),
(36, '2022_03_13_013725_add_company_name_to_contacts_table', 1),
(37, '2022_03_16_075131_add_shipping_date_to_documents_table', 1),
(38, '2022_03_23_142105_add_unit_to_document_items_table', 1),
(39, '2022_04_03_133317_create_tag_tables', 1),
(40, '2021_09_04_062254_create_applied_vats_table', 2),
(41, '2021_09_04_064310_remove_vat_id_column', 2),
(42, '2021_09_10_120836_add_compound_vat_column', 2),
(43, '2022_04_18_132530_create_approvals_table', 2),
(44, '2019_05_03_000001_create_customer_columns', 3),
(45, '2019_05_03_000002_create_subscriptions_table', 3),
(46, '2019_05_03_000003_create_subscription_items_table', 3),
(47, '2022_06_02_133307_create_sales_persons_table', 3),
(48, '2022_06_02_135546_create_sales_persons_table', 4);