--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/4/2022 7:57:51 AM
-- Server version: 5.7.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO quickbilling.payment_methods(id, name, enabled, created_at, updated_at, deleted_at) VALUES
(1, 'Cash', 1, '2022-03-12 15:25:06', '2022-03-12 15:25:06', NULL),
(2, 'Check', 1, '2022-03-12 15:25:12', '2022-03-12 15:25:12', NULL),
(3, 'Bank Transfer', 1, '2022-03-12 15:25:24', '2022-04-22 07:38:29', NULL),
(4, 'Credit Card', 1, '2022-03-12 15:25:33', '2022-03-12 15:25:33', NULL);