--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/4/2022 7:57:55 AM
-- Server version: 5.7.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO quickbilling.personal_access_tokens(id, tokenable_type, tokenable_id, name, token, abilities, last_used_at, created_at, updated_at) VALUES
(93, 'App\\Models\\User', 1, 'api-token', 'ec336d9ec9818eaa36fec27f55d0be7e532cfc3e3ec5a0c6eca923f7b4d4048f', '["*"]', NULL, '2022-05-29 01:06:24', '2022-05-29 01:06:24'),
(94, 'App\\Models\\User', 1, 'api-token', '1eb705fe3be401505b028d9f9799f73114d1a1d7d13c642070ff77763b5d9bb5', '["*"]', NULL, '2022-05-29 14:32:33', '2022-05-29 14:32:33'),
(95, 'App\\Models\\User', 1, 'api-token', '9242ccdc2f72a74f198f2550998b100e67ea413552e917480fcf151959bbfd25', '["*"]', NULL, '2022-05-30 13:23:37', '2022-05-30 13:23:37'),
(96, 'App\\Models\\User', 1, 'api-token', '300736b9fa2256427c7bff68d82133ef5eb845fb27d0def800bac29d1d465451', '["*"]', NULL, '2022-05-30 13:41:57', '2022-05-30 13:41:57'),
(97, 'App\\Models\\User', 1, 'api-token', '960d76b2b4dc9fa4959589b2b223c4b88218c4c75c73d6c600739f30a321cf64', '["*"]', NULL, '2022-05-31 14:54:03', '2022-05-31 14:54:03'),
(98, 'App\\Models\\User', 1, 'api-token', '39fcfe4a682e5f01730313294e824060754fa874e817c17cf53f18b09c8d1663', '["*"]', NULL, '2022-06-02 13:23:54', '2022-06-02 13:23:54'),
(99, 'App\\Models\\User', 1, 'api-token', '0b89864c5c86f047cce26b13450fd4b86bb764f4345efe23931686a1363f59e5', '["*"]', NULL, '2022-06-03 13:02:18', '2022-06-03 13:02:18');