--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/4/2022 7:58:03 AM
-- Server version: 5.7.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO quickbilling.roles(id, name, description, guard_name, created_at, updated_at) VALUES
(1, 'Superuser', 'Superuser', 'web', '2022-03-02 03:08:44', '2022-03-02 03:08:44'),
(2, 'Customer', 'Customer', 'web', '2022-03-02 03:08:54', '2022-03-02 03:08:54'),
(3, 'Admin', 'Admin', 'web', '2022-03-02 03:09:03', '2022-03-02 03:09:03');